### ISSUE TITLE
Linux Converting all template files to utf-8 format remains garbled

### ISSUE THREAD

**Issue by lbb751500349** [mzky/jmeter5.0-cn-report-template#1]
您好，
     麻烦请教下，我是jmeter 5.1.1版本在linux生成html报告。替换了report-template\content\pages路径下的4个.fmkr文件，然后把文件再导出到Windows下查看index报告，发现仍然上乱码。Windows下可以正常汉化

**Comment by mzky** [comment]
看我写的readme： 如想在linux生成html报告，需要将所有模版文件转为UTF-8格式
如果还不行的话 我传给你一份linux下的

**Comment by lbb751500349** [comment]
我昨天下午转换了半天，发现Windows上使用notepad++转UTF-8码转不了，难受的一批。能烦请大佬传一份linux下5.0版本汉化的么，不胜感激~

**Comment by mzky** [comment]
https://pan.baidu.com/s/1XCeNQPMtymlI79kgNCg1ZA#list/path=%2FEasyNmon%2Fjmeter汉化报告模版

**Comment by lbb751500349** [comment]
THS。不过，Linux 版本content文件下css有问题，导致生成报告首页的饼状图KO/OK会乱码，我用Windows版本里content文件替换后就一切正常，牛逼了

**Comment by mzky** [comment]
最近排查了一下 不是css导致的 是content目录下js目录里的dashboard.js.fmkr文件 文件我就不发了 直接跟你说转码方法吧 

1.用notepad++打开dashboard.js.fmkr文件
2.全选并复制内容（重点）
3.在notepad++的“编码”下拉菜单选使用UTF-8编码（这步会导致当前内容乱码）
4.全选并粘贴（把刚复制的正常内容拷贝进来，替换当前转码后乱码的文本内容）
